version: 2.1

jobs:
  lint_code_dockerfile:

    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            apt-get install -y sudo
            python3 -m venv venv
            . venv/bin/activate
            # install python requirements
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths: [./venv]
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint for python code and Dockerfile
          command: |
            . venv/bin/activate
            make lint

  build-scan-push-docker-image:

    docker:
    - image: docker:stable
    # Specify docker tag and version
    environment:
      IMAGE_NAME: mostafaabdelrahman/udacity-capstone
      IMAGE_TAG: v1

    steps:
      - checkout
      - setup_remote_docker
      - checkout
      - run:
          name: Build image
          command: docker build -t "${IMAGE_NAME}:ci" .
      - run:
          name: Scan image
          command: |
            apk add curl bash
            curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- -r "${IMAGE_NAME}:ci"
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag "${IMAGE_NAME}:ci" "${IMAGE_NAME}:${IMAGE_TAG}"
            docker push "${IMAGE_NAME}:${IMAGE_TAG}"
      - store_artifacts:
          path: anchore-reports/

workflows:
  capstone-workflow:
    jobs:
      - lint_code_dockerfile
      - build_scan_push_docker_image:
          requires: [lint_code_dockerfile]
