version: 2.1

jobs:

  build-scan-push-docker-image:

    docker:
    - image: docker:stable
    environment:
      IMAGE_NAME: mostafaabdelrahman/udacity-capstone
      IMAGE_TAG: v1

    steps:
      - checkout
      - setup_remote_docker
      - checkout
      - run:
          name: Build image
          command: docker build -t "${IMAGE_NAME}:ci" .
      - run:
          name: Scan image
          command: |
            apk add curl bash
            curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- -r "${IMAGE_NAME}:ci"
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag "${IMAGE_NAME}:ci" "${IMAGE_NAME}:${IMAGE_TAG}"
            docker push "${IMAGE_NAME}:${IMAGE_TAG}"
      - store_artifacts:
          path: anchore-reports/

workflows:
  capstone-workflow:
    jobs:
      # - linting-job
      - build-scan-push-docker-image
