version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.8.4
jobs:
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build container
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:latest .
      - anchore/analyze_local_image:
          image_name: ${CIRCLE_PROJECT_REPONAME}:latest
          timeout: '500'
          policy_failure: True
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports
          
workflows:
  capstone-ci-workflow:
    jobs:
      - local_image_scan

