version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.8.4

jobs:
  # Scan Docker image
  scan_docker_image:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build container
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:ci .
      - anchore/analyze_local_image:
          image_name: ${CIRCLE_PROJECT_REPONAME}:ci
          timeout: '500'
          
workflows:
  capstone-ci-workflow:
    jobs:
      - scan_docker_image

